#ifndef VWMOTIONWIDGET_GLOBAL_H
#define VWMOTIONWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VWMOTIONWIDGET_LIBRARY)
#  define VWMOTIONWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define VWMOTIONWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // VWMOTIONWIDGET_GLOBAL_H
